name: ngamar
description: A new Flutter project.
repository: https://github.com/moha-b/Pretty-Ui


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: 
  google_fonts: 
  get: 
  surf_lint_rules:
  flutter_svg:
  lottie: 
  dots_indicator:
  animate_do: 
  flutter_otp_text_field: 
  flutter_staggered_animations: 
  like_button: 
  simple_animations: 
  another_stepper: 
  ai_barcode_scanner:
  expandable_text:
  fluttertoast: 
  cupertino_icons: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  image_path_android: assets/images/appIcon.png
  image_path_ios: assets/images/appIcon.png
  ios: true

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
