name: grab_your_cuppa
description: A new Flutter project.
repository: https://github.com/moha-b/Pretty-Ui

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  google_fonts:
  scaled_list: null
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/coffee/
  #   - images/a_dot_ham.jpeg
